# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: env
    type: string
    default: QA

variables:
- group: Test

steps:
- script: echo $(buildnumber)
  displayName: 'Run a one-line script'
