trigger:
- master

# pool:
#   vmImage: ubuntu-latest

stages:
  - stage: "Secret Scan"
    jobs:
    - job: GitGuardianShield
      pool:
        vmImage: 'ubuntu-latest'
      container: gitguardian/ggshield:latest
      steps:
      - script: ggshield scan ci
        env:
          GITGUARDIAN_API_KEY: $(gitguardianApiKey)
