# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: env
    type: string
    default: "QA"

variables:
- group: Test
- name: paravalue
  value: ${{ parameters.env}}

steps:
- script: echo $(paravalue)
- script: echo $(buildnumber)
  displayName: 'Run a one-line script'
- task: replacetokens@5
  inputs:
    rootDirectory: '$(Build.SourcesDirectory)'
    targetFiles: '**/replace-vars.yaml'
    encoding: 'auto'
    tokenPattern: 'custom'
    tokenPrefix: '~{'
    tokenSuffix: '}~'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    actionOnNoFiles: 'continue'
    enableTransforms: false
    enableRecursion: false
    useLegacyPattern: false
    enableTelemetry: true

- script: cat '$(Build.SourcesDirectory)'/replace-vars.yaml

